application: phillycarshare-mobile-kwawatu
version: 1
runtime: python
api_version: 1

handlers:

- url: /test.*
  login: admin
  script: gaeunit.py

- url: /index.html
  script: pcsmobile/handle/wsgi/index.py
  secure: always

- url: /login
  script: pcsmobile/handle/wsgi/index.py
  secure: always

- url: /my_session
  script: pcsmobile/handle/wsgi/my_session.py
  secure: optional

- url: /my_reservations
  script: pcsmobile/handle/wsgi/my_reservation.py
  secure: never

- url: /vehicle_search
  script: pcsmobile/handle/wsgi/vehicle_search.py
  secure: never

- url: /confirm_reservation
  script: pcsmobile/handle/wsgi/confirm_reservation.py
  secure: never

- url: /datetime_picker
  script: pcsmobile/handle/wsgi/datetime_picker.py
  secure: never

- url: /location_picker
  script: pcsmobile/handle/wsgi/location_picker.py
  secure: never

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

