application: phillycarshare-mobile-kwawatu
version: dev
runtime: python
api_version: 1

handlers:

- url: /test.*
  login: admin
  script: gaeunit.py

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /index.html
  script: pcsmobile/handle/wsgi/router.py
  secure: always

- url: /
  script: pcsmobile/handle/wsgi/router.py
  secure: always

- url: /login
  script: pcsmobile/handle/wsgi/router.py
  secure: always

- url: /my_session
  script: pcsmobile/handle/wsgi/router.py
  secure: optional

- url: /my_reservations
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /choose_vehicle
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /choose_location
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /choose_datetime
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /create_reservation
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /confirm_reservation
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /modify_reservation
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /confirm_modification
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /cancel_reservation
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /confirm_cancellation
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /reservation_info
  script: pcsmobile/handle/wsgi/router.py
  secure: never

- url: /about
  script: pcsmobile/handle/wsgi/router.py
  secure: never

